export const cityOfVenezuela = [
  "Barcelona",
  "Barinas",
  "Barquisimeto",
  "Caracas",
  "Ciudad Bolívar",
  "Coro",
  "Cumaná",
  "Gran Roque",
  "Guanare",
  "La Asunción",
  "La Guaira",
  "Los Teques",
  "Maracaibo",
  "Maracay",
  "Maturín",
  "Mérida",
  "Puerto Ayacucho",
  "San Carlos",
  "San Cristóbal",
  "San Felipe",
  "San Fernando de Apure",
  "San Juan de Los Morros",
  "Trujillo",
  "Tucupita",
  "Valencia",
];
